### ISSUE TITLE
Installation is getting stuck with 'npm i @karatelabs/karate'

### ISSUE THREAD

**Issue by DilipMeghwal** [karatelabs/karate-npm#1]
Installation is getting stuck at :

**OS :** Windows 10
**Method tried :** VS Code terminal, Command prompt, PowerShell

```
PS C:\Workspace\Learnings\karate-js> npm i @karatelabs/karate
[##################] / reify:resolve: timing reifyNode:node_modules/yargs Completed in 649ms
```

**Comment by ptrthomas** [comment]
It is possible the download is taking time. Just wait for a few minutes if possible.

@DilipMeghwal this is experimental, please contribute if you can :) we are also creating a central effort here: https://github.com/jbangdev/jbang-npm - not yet released.
