### ISSUE TITLE
Test Cases are not getting executed.

### ISSUE THREAD

**Issue by ncskumar** [karatelabs/karate-npm#13]
I have cloned this and try to execute it. But the test case didnt execute it.

OS: Ventura 13.5 (22G74)
node version: v18.17.0
npm version: 9.6.7

santhoshkumarn@MacBook-Air nodejs-example % npm run test karate

> @karatelabs/karate@0.3.1 test
> node test.js karate

using curl + bash:  -Dkarate.config.dir=karate com.intuit.karate:karate-core:1.3.0:all karate
user1@MacBook-Air nodejs-example % 
user1@MacBook-Air nodejs-example % 
user1@MacBook-Air nodejs-example % npm run test karate/httpbin.feature 

> @karatelabs/karate@0.3.1 test
> node test.js karate/httpbin.feature

using curl + bash:  -Dkarate.config.dir=karate com.intuit.karate:karate-core:1.3.0:all karate/httpbin.feature
user1@MacBook-Air nodejs-example %

**Comment by ptrthomas** [comment]
this repository is not an example that you can clone and run, please read the README carefully

I just tried a sample as per the instructions and ` npm run test karate` worked: https://github.com/ptrthomas/karate-npm-example

**Comment by ncskumar** [comment]
Thanks for the quick response. I have tried the example you have shared here but result is same.

<img width="624" alt="image" src="https://github.com/karatelabs/karate-npm/assets/96577090/46652951-56b3-45f0-a96e-bc53f6631380">

I dont see any output after executing the command 'npm run test karate'

**Comment by ncskumar** [comment]
In MacOS the library might have some issues, where as in Ubuntu it worked.

**Comment by ptrthomas** [comment]
sorry I can't replicate. anyone is welcome to replicate or submit a PR. one tip is please remove your local maven cache, at least the `com.intuit.karate` parts and try

**Comment by ncskumar** [comment]
I am able to run it now. Its because of Maven. I have uninstalled all plugins and now it started working.
