### ISSUE TITLE
Can we use Karate framework for API automation testing in Node js based project using Karate NPM ?

### ISSUE THREAD

**Issue by kesavarao-EB** [karatelabs/karate-npm#15]
Are there any samples or reference talk about this usage of Karate framework in Typescript based project ?

i tried to setup  following read me and executed the tests. but i dont see test running. got stuck after  "waiting for 2 features to complete" 
no error or nothing shown up

`using jbang:  com.intuit.karate:karate-core:1.4.1:all ./src/features -t @create_user
[jbang] Resolving dependencies...
[jbang] Dependencies resolved
19:40:22.400 [main] INFO  com.intuit.karate - Karate version: 1.4.1
19:40:22.579 [main] DEBUG com.intuit.karate.Suite - [config] karate-config.js
19:40:22.623 [main] DEBUG com.intuit.karate.Suite - waiting for 2 features to complete`

**Comment by ptrthomas** [comment]
@kesavarao-EB not really, at the end of the day karate is a CLI command, and karate-npm just tries to make it work in a nodejs or npm project

I suggest you try the docker or CLI option and see how it goes: https://github.com/karatelabs/karate/wiki/Get-Started:-Other-Runtime-Options

**Comment by kesavarao-EB** [comment]
@ptrthomas Does this mean "karate-npm" will not work ?
bcas i have followed the readme of karate-npm and my test got stuck in execution.

**Comment by ptrthomas** [comment]
@kesavarao-EB it seems to work for most folks (see other closed issues). you are welcome to contribute a PR

**Comment by kesavarao-EB** [comment]
@ptrthomas  FYI karate-npm is not working , got stuck . No error or nothing displayed.

Steps:
1. Just clone this same repo https://github.com/karatelabs/karate-npm
2. followed readme for setup and did npm install
3. npm run test

`k@k karate-npm % npm run test

> starter-karate-dsl-npm@1.0.0 test
> node ./src/test.js

using jbang:  com.intuit.karate:karate-core:1.4.1:all src/features/users/users.feature 
10:24:46.996 [main] INFO  com.intuit.karate - Karate version: 1.4.1
10:24:47.165 [main] DEBUG com.intuit.karate.Suite - [config] karate-config.js`

Would you mind trying once from your end. Entire organization may move to karate . Evaluation in progress. Just that all our dev code base is typescript. Not sure without Java and maven project addon into typescript project, we can use karate. Though using docker, running test eveytime docker is not a viable solution for us. we want to develop and tets locally without external dependencies.
