### ISSUE TITLE
Could not resolve dependencies when running npm i @karatelabs/karate

### ISSUE THREAD

**Issue by SerenaIce** [karatelabs/karate-npm#18]
Environment:
OS: macos
node: v20.14.0
jbang: v0.116.0

Error:
[jbang] [ERROR] Could not resolve dependencies: Failed to collect dependencies at com.intuit.karate:karate-core:jar:all:LATEST

Description
I tried to install karate into my nodejs project, got the same error with running npm install in the example project at my local MacBook. Do you have any idea about the cause?

![image](https://github.com/karatelabs/karate-npm/assets/43363062/97813309-a40c-4567-bcb7-5031ed81210d)

**Comment by ptrthomas** [comment]
no idea, maybe your network does not allow downloading jars. to troubleshoot jbang you can do this:

```
jbang cache clear
jbang karate@karatelabs -h
```

as a workaround you can try other ways of running (e.g. using the standalone JAR): https://github.com/karatelabs/karate/wiki/Get-Started:-Other-Runtime-Options

**Comment by SerenaIce** [comment]
Thank you @ptrthomas for the suggestions. It is related to my networks. I must set proxies to make it run and now get it solved.
