### ISSUE TITLE
Nothing happen after execution - Java 17.0.1 - Node 16.14.0 - NPM 8.5.0

### ISSUE THREAD

**Issue by charlyautomatiza** [karatelabs/karate-npm#2]
After following the steps to run on windows, nothing happen, there ir no error and no execution log.

After adding `@karatelabs/karate` dependency and install.

`npm i`

`SO: Windows 10 Home`

Java, NPM and Node version:

```bash
C:\dev\api>npm -v
8.5.0

C:\dev\api>node -v
v16.14.0

C:\dev\api>echo %JAVA_HOME%
C:\Program Files\Java\jdk-17.0.1

```
My test.js

```js
#! /usr/bin/env node
const karate = require('@karatelabs/karate');
karate.exec();
```

My package.json.

```json
{
  "name": "api",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "node test.js"
  },
  "keywords": [],
  "author": "CharlyAutomatiza",
  "license": "ISC",
  "devDependencies": {
    "@karatelabs/karate": "^0.2.1"
  }
}
```

But nothing happen when I run in `cmd`.

```bash
C:\dev\api>npm run test karate/httpbin.feature

> api@1.0.0 test
> node test.js "karate/httpbin.feature"

using curl + bash: com.intuit.karate:karate-core:1.2.0.RC5:all karate/httpbin.feature

C:\dev\api>
```

**Comment by ptrthomas** [comment]
@charlyautomatiza thank you for reporting this - we do seem to have some issues on windows, see #1 

it would be great if you can contribute. meanwhile I've created this issue at the jbang-npm project https://github.com/jbangdev/jbang-npm/issues/4

the workaround would be for you to install jbang manually following the instructions here - and then repeat the `npm i`: https://www.jbang.dev/documentation/guide/latest/installation.html

it would be great if you can let me know if it works after you have manually installed jbang

**Comment by charlyautomatiza** [comment]
Hi @ptrthomas Thanks for the quick reply.
I can confirm that after installing `jbang` manually my karate script works.

To install `jbang `manually in Windows Powershell:

`iex "& { $(iwr -useb https://ps.jbang.dev) } app setup"`

**Comment by ptrthomas** [comment]
@charlyautomatiza really appreciate the quick feedback !

**Comment by rahulmr** [comment]
Not sure if this is same issue but I am getting below error when I am trying from powershell.

```
PS D:\personal\karate_projects\karate-npm> pwsh --version
PowerShell 7.2.2
```
npm details ::
```
PS D:\personal\karate_projects\karate-npm> npm -v
8.6.0
PS D:\personal\karate_projects\karate-npm> node -v
v17.8.0
PS D:\personal\karate_projects\karate-npm>
```

jbang details:
```
PS D:\personal\karate_projects\karate-npm> jbang version
0.92.2
```


When I clone this repo and perform `npm i` I am getting below issue.

```
PS D:\personal\karate_projects\karate-npm> npm i

> @karatelabs/karate@0.2.1 preinstall
> node preinstall.js

pre-installing karate ...
using jbang: com.intuit.karate:karate-core:LATEST:all
[jbang] Resolving dependencies...
[jbang] com.intuit.karate:karate-core:jar:all:LATEST
[jbang] [ERROR] Could not resolve dependencies from mavencentral=https://repo1.maven.org/maven2/
Unable to collect/resolve dependency tree for a resolution due to: Could not find artifact com.intuit.karate:karate-core:jar:all:LATEST, caused by: Could not find artifact com.intuit.karate:karate-core:jar:all:LATEST
  Could not find artifact com.intuit.karate:karate-core:jar:all:LATEST
[jbang] Run with --verbose for more details
pre-install of karate complete

up to date, audited 22 packages in 3s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS D:\personal\karate_projects\karate-npm>

```


I check the url for maven => https://repo1.maven.org/maven2/ 
But there is karate or karate-core folder in it.

![image](https://user-images.githubusercontent.com/10260232/162639847-30e66811-6b97-493c-9554-8239cf862b47.png)

**Comment by ptrthomas** [comment]
@rahulmr looks like you cloned the project and installed it ? that won't work because we haven't made the release of karate-all. it may work if you set `karate.version = '1.2.0.RC5` as per the instructions.

please create a node project and use `npm install` to test 0.2.1

**Comment by rahulmr** [comment]
Yes it is working now with `'1.2.0.RC5'`.

**Comment by ptrthomas** [comment]
closing as this will work correctly after releasing karate-npm 0.2.2

**Comment by ammar01** [comment]
Hi Peter, I'm sorry to report we're having this same problem with the latest version of karate-npm. 

Installing karate-npm and running tests was fine until about a month ago. Back then with karate-npm version 0.2.3, we'd get this popup on installation:
![image](https://user-images.githubusercontent.com/996294/235240072-82a7de33-54c7-4dac-9e65-7382ffab0c7b.png)
The jbang dependency would still install fine.  The command `npm run test` would then execute our tests.

Today, when I do a clean install of 0.2.3, the installation still works but when I try to run a test, I see this output and no test executes. 
![image](https://user-images.githubusercontent.com/996294/235240942-f2182093-8b04-4bc4-908c-24167cb0caa3.png)

When I try to do a clean install of the latest karate-npm version 0.3.1, the Windows popup above still appears, but now I also see a stack trace.
![image](https://user-images.githubusercontent.com/996294/235242653-f1eab561-757d-4ff2-b8f0-6ede0d045d08.png)
Also, the node_packages folder disappears after the install process finishes/crashes.

Any ideas would be greatly appreciated.
![image](https://user-images.githubusercontent.com/996294/235232917-e9bb441d-61a9-4ce3-a76e-10a98ae14c91.png)

**Comment by ptrthomas** [comment]
@ammar01 yes windows is known to be problematic. do consider contributing code or helping others to do so

**Comment by ammar01** [comment]
> Hi Peter, I'm sorry to report we're having this same problem with the latest version of karate-npm.
> 
> Installing karate-npm and running tests was fine until about a month ago. Back then with karate-npm version 0.2.3, we'd get this popup on installation: ![image](https://user-images.githubusercontent.com/996294/235240072-82a7de33-54c7-4dac-9e65-7382ffab0c7b.png) The jbang dependency would still install fine. The command `npm run test` would then execute our tests.
> 
> Today, when I do a clean install of 0.2.3, the installation still works but when I try to run a test, I see this output and no test executes. ![image](https://user-images.githubusercontent.com/996294/235240942-f2182093-8b04-4bc4-908c-24167cb0caa3.png)
> 
> When I try to do a clean install of the latest karate-npm version 0.3.1, the Windows popup above still appears, but now I also see a stack trace. ![image](https://user-images.githubusercontent.com/996294/235242653-f1eab561-757d-4ff2-b8f0-6ede0d045d08.png) Also, the node_packages folder disappears after the install process finishes/crashes.
> 
> Any ideas would be greatly appreciated. ![image](https://user-images.githubusercontent.com/996294/235232917-e9bb441d-61a9-4ce3-a76e-10a98ae14c91.png)

For anyone who comes across this closed issue in future, the solution I found is as mentioned in the documentation. Manually install jbang first. I downloaded the latest version zip from https://github.com/jbangdev/jbang/releases, extracted it to a folder and added the /bin folder in there to my PATH environment variable. After this, doing an npm install of karate-npm was successful without any error.
