### ISSUE TITLE
How can I connect to DB with javascript?

### ISSUE THREAD

**Issue by rsantosr** [karatelabs/karate-npm#6]
Hi everyone!

I try to use karate-npm but I can't connect to DB by javascript. 

Also, when I try to use javascript, I need to begin with the "function" word, and I can't use a library npm.

Please, can you help me?

**Comment by ptrthomas** [comment]
@rsantosr unfortunately karate uses a different JS engine (not node), so standard npm concepts do not apply. it may be possible to load a JS lib if you `read()` the entry-point JS file.

karate-npm is experimental. as of now if you need to call a DB, the recommended way is to use Java: https://stackoverflow.com/a/71598261/143475

I also recommend trying alternative approaches like calling a system process: https://stackoverflow.com/a/73321719/143475
